// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NCUT_Market.Infrastructure.Persistence;

#nullable disable

namespace NCUT_Market.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NCUT_Market.Core.Entities.Announcement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("expired_at");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("published_at");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "PublishedAt")
                        .HasDatabaseName("idx_announcements_status_published_at");

                    b.ToTable("announcements", (string)null);
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("idx_categories_parent_id");

                    b.HasIndex("Status", "SortOrder")
                        .HasDatabaseName("idx_categories_status_sort_order");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Conversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BuyerId")
                        .HasColumnType("bigint")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("BuyerLastReadAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("buyer_last_read_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("last_message_at");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductThumbnailKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_thumbnail_key");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("product_title");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.Property<DateTime>("SellerLastReadAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("seller_last_read_at");

                    b.Property<DateTime?>("TransactionProposedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("transaction_proposed_at");

                    b.Property<long?>("TransactionProposedById")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_proposed_by_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TransactionProposedAt")
                        .HasDatabaseName("idx_conversations_transaction_proposed_at");

                    b.HasIndex("TransactionProposedById");

                    b.HasIndex("BuyerId", "LastMessageAt")
                        .HasDatabaseName("idx_conversations_buyer_id_last_message_at");

                    b.HasIndex("ProductId", "BuyerId")
                        .IsUnique()
                        .HasDatabaseName("uk_conversations_product_id_buyer_id");

                    b.HasIndex("SellerId", "LastMessageAt")
                        .HasDatabaseName("idx_conversations_seller_id_last_message_at");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.DormitoryArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uk_dormitory_areas_name");

                    b.HasIndex("Status", "SortOrder")
                        .HasDatabaseName("idx_dormitory_areas_status_sort_order");

                    b.ToTable("dormitory_areas", (string)null);
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("content");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_id");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("ConversationId", "Id")
                        .HasDatabaseName("idx_messages_conversation_id_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("read_at");

                    b.Property<long?>("RelatedProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("related_product_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RelatedProductId")
                        .HasDatabaseName("idx_notifications_related_product_id");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("idx_notifications_user_id_is_read_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BuyerConfirmedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("buyer_confirmed_at");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<byte>("Condition")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DormitoryAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("dormitory_area_id");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("last_activity_at");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("published_at");

                    b.Property<DateTime?>("SellerConfirmedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("seller_confirmed_at");

                    b.Property<long>("SellerId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("sold_at");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("TransactionAcceptedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("transaction_accepted_at");

                    b.Property<long?>("TransactionBuyerId")
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_buyer_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_products_category_id");

                    b.HasIndex("DormitoryAreaId")
                        .HasDatabaseName("idx_products_dormitory_area_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("idx_products_seller_id");

                    b.HasIndex("TransactionBuyerId")
                        .HasDatabaseName("idx_products_transaction_buyer_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_products_status_created_at");

                    b.HasIndex("Status", "LastActivityAt")
                        .HasDatabaseName("idx_products_status_last_activity_at");

                    b.HasIndex("Status", "TransactionAcceptedAt")
                        .HasDatabaseName("idx_products_status_transaction_accepted_at");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_price", "`price` >= 0");
                        });
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.ProductImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<ulong>("FileSize")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("file_size");

                    b.Property<uint>("Height")
                        .HasColumnType("int unsigned")
                        .HasColumnName("height");

                    b.Property<string>("LargeKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("large_key");

                    b.Property<string>("MediumKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("medium_key");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("mime_type");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("ThumbnailKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("thumbnail_key");

                    b.Property<uint>("Width")
                        .HasColumnType("int unsigned")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "SortOrder")
                        .HasDatabaseName("idx_product_images_product_id_sort_order");

                    b.ToTable("product_images", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_images_file_size", "`file_size` > 0");

                            t.HasCheckConstraint("ck_product_images_height", "`height` > 0");

                            t.HasCheckConstraint("ck_product_images_width", "`width` > 0");
                        });
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarKey")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nickname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password_reset_code");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("password_reset_expires_at");

                    b.Property<byte>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("role");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uk_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Category", b =>
                {
                    b.HasOne("NCUT_Market.Core.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Conversation", b =>
                {
                    b.HasOne("NCUT_Market.Core.Entities.User", "Buyer")
                        .WithMany("BuyerConversations")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCUT_Market.Core.Entities.Product", "Product")
                        .WithMany("Conversations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCUT_Market.Core.Entities.User", "Seller")
                        .WithMany("SellerConversations")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCUT_Market.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TransactionProposedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Buyer");

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Message", b =>
                {
                    b.HasOne("NCUT_Market.Core.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCUT_Market.Core.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Notification", b =>
                {
                    b.HasOne("NCUT_Market.Core.Entities.Product", "RelatedProduct")
                        .WithMany("Notifications")
                        .HasForeignKey("RelatedProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCUT_Market.Core.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelatedProduct");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Product", b =>
                {
                    b.HasOne("NCUT_Market.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCUT_Market.Core.Entities.DormitoryArea", "DormitoryArea")
                        .WithMany("Products")
                        .HasForeignKey("DormitoryAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCUT_Market.Core.Entities.User", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCUT_Market.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("TransactionBuyerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("DormitoryArea");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.ProductImage", b =>
                {
                    b.HasOne("NCUT_Market.Core.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.DormitoryArea", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.Product", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Images");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("NCUT_Market.Core.Entities.User", b =>
                {
                    b.Navigation("BuyerConversations");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Products");

                    b.Navigation("SellerConversations");
                });
#pragma warning restore 612, 618
        }
    }
}
